import { FormEvent, useState } from "react";
import { Link, useSearchParams } from "react-router";
import { ArrowLeft, Eye, EyeOff, LockKeyhole } from "lucide-react";
import BrandLogo from "../components/BrandLogo";
import LanguageToggle from "../components/LanguageToggle";
import { resetPasswordRequest } from "../api";
import { useLanguage } from "../context/LanguageContext";

export default function ResetPassword() {
  const { t } = useLanguage(); const [params] = useSearchParams(); const token = params.get("token") ?? ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (password.length < 8) return setError(t("passwordRequirement")); if (password !== confirm) return setError(t("passwordMismatch")); setLoading(true); try { await resetPasswordRequest(token, password); setSuccess(true); } catch (err) { setError(err instanceof Error ? err.message : t("resetError")); } finally { setLoading(false); } };
  return <div className="min-h-screen flex flex-col justify-center items-center px-6 py-12 bg-background"><div className="absolute right-4 top-4"><LanguageToggle /></div><div className="w-full max-w-md"><Link to="/"><BrandLogo /></Link><div className="mt-10"><Link to="/login" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-10"><ArrowLeft size={16} /> {t("backToLogin")}</Link><div className="mb-8"><div className="mb-4 grid h-12 w-12 place-items-center rounded-full bg-primary/10 text-primary"><LockKeyhole size={22} /></div><h1 className="font-['DM_Serif_Display'] text-4xl text-foreground mb-2">{success ? t("passwordChanged") : t("resetTitle")}</h1><p className="text-muted-foreground text-sm">{success ? t("passwordChangedSubtitle") : t("resetSubtitle")}</p></div>{success ? <Link to="/login" className="block w-full text-center bg-primary text-white py-3.5 rounded-xl font-semibold text-sm">{t("backToLogin")}</Link> : !token ? <ErrorState text={t("invalidResetLink")} /> : <form onSubmit={submit} className="space-y-5"><PasswordField id="password" label={t("newPassword")} value={password} onChange={setPassword} show={show} setShow={setShow} /><PasswordField id="confirm" label={t("confirmPassword")} value={confirm} onChange={setConfirm} show={show} setShow={setShow} />{error && <div role="alert" className="text-sm text-destructive">{error} {error.includes("expired") && <Link to="/forgot-password" className="underline">{t("requestAnother")}</Link>}</div>}<button disabled={loading} className="w-full bg-primary text-white py-3.5 rounded-xl font-semibold text-sm disabled:opacity-60">{loading ? t("changingPassword") : t("changePassword")}</button></form>}</div></div></div>;
}
function PasswordField({ id, label, value, onChange, show, setShow }: { id: string; label: string; value: string; onChange: (value: string) => void; show: boolean; setShow: (value: boolean) => void }) { return <div><label htmlFor={id} className="block text-sm font-medium mb-2">{label}</label><div className="relative"><input id={id} type={show ? "text" : "password"} minLength={8} required value={value} onChange={(e) => onChange(e.target.value)} className="w-full px-4 py-3 pr-12 bg-input-background border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary/30" /><button type="button" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)} className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground">{show ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></div>; }
function ErrorState({ text }: { text: string }) { const { t } = useLanguage(); return <div className="rounded-xl border border-destructive/20 bg-destructive/10 px-4 py-4 text-sm text-destructive">{text} <Link to="/forgot-password" className="underline">{t("requestAnother")}</Link></div>; }
